name: Build AntiStickerBot

on:
  push:
    branches: [ master ]
    paths:
      - 'AntiStickerBot/**'
  pull_request:
    paths:
      - 'AntiStickerBot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: anti-sticker-bot
        context: AntiStickerBot
        registry: ${{ secrets.PUSH_REPO }}
        username: ${{ secrets.PUSH_USER }}
        password: ${{ secrets.PUSH_PASSWD }}
        default_branch: master
        no_push: ${{ github.event_name == 'pull_request' }}
